# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-17 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170216_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-modified_date']},
        ),
    ]
