# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170217_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=0, upload_to=b'blog_images/%Y/%m/%/%d/'),
            preserve_default=False,
        ),
    ]
