# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=b'blog_images/%Y/%m/%d/'),
        ),
    ]
